services:
    prod:
        container_name: erelya-prod
        image: erelya:latest
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file: .env.prod
    db:
        image: postgres:18
        container_name: erelya-db
        restart: unless-stopped
        env_file: .env
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "${DATABASE_PORT}:${DATABASE_PORT}"
        volumes:
            - data:/var/lib/postgresql

volumes:
    data: {}